###
GET http://localhost:8080/index/get?name=howard

###
POST http://localhost:8080/index/post
Content-Type: application/json

{"name":"howard"}

###
POST http://localhost:8080/index/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="history.txt"
Content-Type: multipart/form-data
</Users/liuxh/history.txt
--WebAppBoundary--

###
GET http://localhost:8080/index/download
